# Generated by Django 4.2 on 2023-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_mechanic_cpassword_alter_mechanic_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
